TYPO3-Documentation/TYPO3CMS-Tutorial-Editors

Documentation/Pages/OtherFeatures/Index.rst, Documentation/fr_FR/ContentElements/Content/Index.rst, Documentation/fr_FR/ContentElements/CreatingContent/Index.rst, Documentation/fr_FR/ContentElements/Images/Index.rst, Documentation/fr_FR/Index.rst, Documentation/fr_FR/Introduction/Index.rst, Documentation/fr_FR/Login/Index.rst, Documentation/fr_FR/Pages/AddingMultiple/Index.rst, Documentation/fr_FR/Pages/OtherFeatures/Index.rst, Documentation/fr_FR/Pages/PageProperties/Index.rst, Documentation/fr_FR/Pages/WorkingWithPages/Index.rst
First corrections after review online.
=> [TASK] French correction

Documentation/AccessControl/Login/Index.rst
=> TASK: Fix block "Access rights"

Documentation/Index.rst, Documentation/Settings.cfg, composer.json
As master is set for 10, as branches for 9.5 and 8.7 already were
created.
=> Fix version and release for master

Documentation/Pages/WorkingWithPages/Index.rst
Corrected typo (extra p in "dropping")
=> Typo correction

Documentation/Introduction/Index.rst
- Point out which chapters to read in "Getting Started".
Before, it was recommended to read the entire "Getting Started Tutorial"
which does not make sense if the reader neither has access
nor expertise to perform administration tasks.
Releases: master, 10.4, 9.5
=> Update Introduction chapter

Documentation/Settings.cfg
Edit on GitHub did not work - it directed to the draft branch. 
Should be "master"
=> Fix github_branch

Documentation/Login/Index.rst
See TYPO3-Documentation/T3DocTeam#165 for details.
=> [TASK] Unify top-level domain of dummy urls

.editorconfig, Documentation/Index.rst, Documentation/Introduction/Index.rst
See TYPO3-Documentation/T3DocTeam#166 for details.
=> [TASK] Unify placeholder syntax

Documentation/HelpInside/Index.rst, Documentation/HelpInside/KeyboardCommands/Index.rst
=> [TASK] Add section on keyboard commands

.editorconfig, Documentation/Includes.rst.txt, Documentation/Settings.cfg, README.rst
intersphinx_mapping, github_branch etc
=> [TASK] Change settings from master to main

Documentation/About.rst, Documentation/AccessControl/Login/Index.rst, Documentation/HelpInside/Index.rst, Documentation/Languages/Index.rst, Documentation/Pages/PageTypes/Index.rst, Documentation/Settings.cfg
=> [TASK] Replace wiki links

Documentation/About.rst, Documentation/AccessControl/Login/Index.rst, Documentation/Languages/Index.rst, Documentation/Pages/PageTypes/Index.rst, Documentation/Settings.cfg
=> [TASK] Replace wiki links v11

Documentation/Introduction/Index.rst, Documentation/Languages/Index.rst, Documentation/Settings.cfg
=> [TASK] Replace wiki links v9

Documentation/Introduction/Index.rst, Documentation/Settings.cfg
=> [TASK] Replace wiki links v8

Documentation/Introduction/Index.rst, Documentation/Settings.cfg
=> [TASK] Replace wiki links v7

Documentation/Index.rst, Documentation/Login/Index.rst
It is part of the sylabus for the Editors certification
=> [TASK] Restore the page about login

Documentation/ContentElements/CreatingContent/Index.rst
For the "Creating Content"-Page:
Fix typos, link to the bootstrap package with dependency information, use a note notation, mark "TYPO3 Core" bold and improve language.
=> Update creating content

Documentation/AccessControl/Index.rst, Documentation/ListModule/Index.rst, Documentation/ListModule/UsingEffectively/Index.rst
[+] Move introduction paragraph into the first page of
the List Module chapter
[-]  Remove "filler" text from Access Control chapter
=> [Task] Update introduction text for list module and access control

Documentation/Login/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/422
Releases: main, 12.4
=> [FEATURE] Enable password view at backend login

Documentation/Pages/PageTypes/Index.rst
Add also a small section about custom page types.
Releases: main, 12.4, 11.5
=> [TASK] Revise page types chapter

Documentation/Pages/PageTypes/Index.rst
Add also a small section about custom page types.
Releases: main, 12.4, 11.5
=> [Backport 12.4] [TASK] Revise page types chapter (#126)

Documentation/Pages/PageTypes/Index.rst
Add also a small section about custom page types.
Releases: main, 12.4, 11.5
=> [Backport 11.5] [TASK] Revise page types chapter (#126)

Documentation/Pages/PageProperties/Index.rst
=> Overhaul Page properties

Documentation/ContentElements/CreatingContent/Index.rst
=> Overhaul Creating content

Documentation/Index.rst, Documentation/Localization.ru_RU/Index.rst
=> [BUGFIX] Add missing reference for concepts

Documentation/Index.rst
=> [BUGFIX] Add missing reference for concepts (#154)

Documentation/Localization.ru_RU/Login/Index.rst, Documentation/Login/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/813
Releases: main
=> [FEATURE] #87889 - Make backend URL configurable

Documentation/Includes.rst.txt
=> [TASK] Add end of life hint & delete unused content in Includes.rst.txt

Documentation/ListModule/UsingEffectively/Index.rst
=> Using the list module

Documentation/AccessControl/Index.rst, Documentation/Concepts/Index.rst, Documentation/ContentElements/Index.rst, Documentation/Index.rst, Documentation/ListModule/Index.rst, Documentation/Pages/Index.rst
=> [TASK] Migrate deprecated card container

Documentation/SearchEngineOptimization/Index.rst
=> [BUGFIX] Remove broken Screenshot

Documentation/HelpInside/KeyboardCommands/Index.rst
=> Add anchors to shortcuts

Documentation/Pages/AddingMultiple/Index.rst, Documentation/Pages/CreatingPages/Index.rst, Documentation/Pages/PageProperties/Index.rst, Documentation/Pages/PageTypes/Index.rst, Documentation/Pages/WorkingWithPages/Index.rst
This commit replaces the old v11 tutorials with new
videos recorded for v13.
[+] Update "Creating Pages" video
[+] Update "Working With Pages" video
[+] Update "Page Types" video
[+] Add new "Creating Multiple Pages" video
[+] Add new "Page Properties" video
=> [TASK] Replace video tutorials in Pages chapter

Documentation/Pages/WorkingWithPages/Index.rst
Closes https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/897
Releases: main, 13.4
=> [TASK] Document comma-separated filtering of page tree filter

Documentation/ContentElements/EditingContent/Index.rst
This commit replaces the old editing content video with a new version for TYPO3 version 13
[-] Remove old video at the bottom of the page
[+] Add new video at top of page
Please port to v13 branch
=> Add new Editing Content Video

Documentation/ContentElements/Content/Index.rst
This commit adds the new Managing Content video to the top of the page
=> Add Managing Content video
